### ISSUE TITLE
G4MTRunManager not working properly

### ISSUE THREAD

**Issue by rposer** [HaarigerHarald/geant4_pybind#15]
First and foremost, thank you for the great package. Most convenient and quickest installation of Geant4 I ever had!

I noticed that `geant4_pybind` gets stuck when using `G4MTRunManager` either directly or via the `G4RunManagerFactory` when used with Windows 10. I recalled that some years ago, Geant4 only had multi-threading support for UNIX-based OSs. Therefore, I tried to run the same experiment in a Docker container based on Ubuntu.

In both cases, the physics processes get initialized and then the script is stuck. When switching to a serial run manager, everything seems to work fine.

I understand that this is most likely a side project of yours. Just wanted to let you know!

Thank you,
Philipp

PS: I just found that you also reverted back to using a serial manager in the examples. I guess you are already aware of this issue.

**Comment by HaarigerHarald** [comment]
Might be that there is somewhere a `gil_scoped_release` missing, if you don't mind sharing your sim I can have a look.

Yet, the multithreaded stuff is probably somewhat incomplete and due to the nature of python and its [global interpreter lock](https://docs.python.org/3/glossary.html#term-global-interpreter-lock) you also won't gain any performance from using the Geant4 multithreaded run managers.

If you absolutely need better performance look into the [multiprocessing module](https://docs.python.org/3/library/multiprocessing.html).

**Comment by rposer** [comment]
Thank you for the quick reply!

In my imagination (not a CS major), the GIL had no impact when native C or C++ code is merely wrapped (at least that is what I thought to have observed when using ctypes). However, I have no experience with the GIL, pybind11, and large object-oriented frameworks. Apparently, the GIL is a problem when there are interactions with Python objects.

Anyways. For me it's fine to just run the script x times in parallel and then accumulate the results.

Thank you,
Philipp
