### ISSUE TITLE
Support for interactive use?

### ISSUE THREAD

**Issue by drbenmorgan** [HaarigerHarald/geant4_pybind#2]
I've been trying out the bindings - **very** nice work (Geant4 has a plan to migrate to pybind11, so would be interested to see if we could collaborate more here)!

One minor gotcha I encountered when naively trying to import the package from interactive Python (NB: from a local build, not a `pip install`):

```console
$ PYTHONPATH=$PWD/source python3.9                                                        
Python 3.9.8 (main, Nov 10 2021, 06:03:50) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import geant4_pybind
Traceback (most recent call last):
  File "<string>", line 124, in <module>
AttributeError: module '__main__' has no attribute '__file__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: initialization failed
```

I think I've traced that to the `datainit.py` module getting called, and specifically the line:

https://github.com/HaarigerHarald/geant4_pybind/blob/d9c774a04156b1518795bafbd7819a1b8a03f7ea/source/datainit.py#L123

Whilst in general interactive use _probably_ isn't the primary use case, it would be useful to support it. I'm happy to look at ways to fix this, but let me know what you think!

**Comment by HaarigerHarald** [comment]
Hi,
thanks, yes of course help and collaboration is always welcome! Also feel free to incorporate this partially or fully into the official bindings.

Regarding the issue, unfortunately I think this is a slight bit more problematic as it prevents imports in jupyter notebooks. I’m still not sure though why it didn’t occur in the jupyter vscode extension that I tested with. However, it should be fixed with 9a1f18d0eb1dc5cb24b01ed7b5fd6c6954927f32 by simply checking a global variable, which is probably the better approach in this case anyways.
