### ISSUE TITLE
Visualization problem

### ISSUE THREAD

**Issue by shulga-alexey** [HaarigerHarald/geant4_pybind#23]
Hello.
I have issues using the visualization package. When I execute example [B1](https://github.com/HaarigerHarald/geant4_pybind/tree/main/examples/B1) geant4_pybind python code the UI session starts but do not visualize anything. The process freezes in the state shown in the screenshot.
![Снимок экрана (4)](https://github.com/HaarigerHarald/geant4_pybind/assets/123380626/7c062e94-c62d-4b33-837b-5f4bf732c478)
If I run the Geant4 examples , the visualization works.
I'm not sure what the reason is, but I hope someone can give me a hint on what might be wrong here.
I'm using WSL with Ubuntu 22.04 and python 3.10 .
![Снимок экрана (3)](https://github.com/HaarigerHarald/geant4_pybind/assets/123380626/c9b05c69-388b-4fae-a2c1-7d9c12c0d5a2)
P.S. Sorry for my English

**Comment by HaarigerHarald** [comment]
The Qt opengl visualization driver has issues on WSL, I'm not really sure what the issue exactly is but it has something to do with the available opengl features. Either use the windows version if you are on windows or if you need to use Linux a different VM, a dual boot or self compiled version with `opengl-x11` visualization instead of Qt. There is not much one can do.
